# Generated by Django 4.1.7 on 2023-05-06 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Control_content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomination', models.BooleanField(default=False)),
                ('vote', models.BooleanField(default=False)),
                ('contention', models.BooleanField(default=False)),
                ('result', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Control Content',
            },
        ),
        migrations.CreateModel(
            name='Parking_spot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('parkingphoto', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='User_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=50)),
                ('phone_no', models.IntegerField(null=True)),
                ('email', models.EmailField(max_length=50, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('birthdate', models.DateField(null=True)),
                ('reservation_status', models.BooleanField(default=False)),
                ('Userkey', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parking_spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.parking_spot')),
                ('worker_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='training.user_model')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField(max_length=30, null=True)),
                ('price', models.IntegerField(max_length=10)),
                ('User_Model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_to_foreign_key_2', to='training.user_model')),
                ('parking_spot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_to_foreign_key_1', to='training.parking_spot')),
            ],
        ),
        migrations.CreateModel(
            name='Contention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('nominee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.worker')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.user_model')),
            ],
        ),
        migrations.CreateModel(
            name='Admin_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=50)),
                ('Userkey', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
