# Generated by Django 4.2.1 on 2023-05-14 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_alter_parking_spot_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking_spot',
            name='governorate',
            field=models.CharField(default='C', max_length=52),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_model',
            name='city',
            field=models.CharField(default='C', max_length=52),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_model',
            name='governorate',
            field=models.CharField(default='C', max_length=52),
            preserve_default=False,
        ),
    ]
